export const homeValues = [
  {
    icon: "handshake",
    title: "Integrity",
    body: "Clear communication, honest thinking, and no hidden agendas. Trust is built through transparency, especially when things are complex.",
  },
  {
    icon: "verified",
    title: "Excellence",
    body: "Excellence lives in the details people may not notice, but always feel. The work should be sharp, reliable, and deeply considered.",
  },
  {
    icon: "groups",
    title: "Collaboration",
    body: "Strong solutions are built through teamwork. Listening, alignment, and shared language turn different perspectives into one direction.",
  },
  {
    icon: "commit",
    title: "Commitment",
    body: "I stay fully invested from brief to delivery, making innovation practical, secure, and useful for real teams, within real constraints and timelines.",
  },
] as const;

export const expertiseAreas = [
  {
    icon: "strategy",
    title: "Strategy",
    items: ["Shape product direction", "Turn complexity into clarity", "Align teams around decisions"],
  },
  {
    icon: "emoji_objects",
    title: "Innovation",
    items: ["Facilitate workshops & sprints", "Turn ideas into tested concepts", "Build adoption rituals"],
  },
  {
    icon: "hub",
    title: "AI Workflows",
    items: ["Map AI into real workflows", "Design agentic automation", "Enable teams through practice"],
  },
] as const;

export const projectCards = [
  {
    category: "MONITOR MODULE",
    title: "The Big RED BUTTON",
    href: "/experience/the-big-red-button",
    summary: "Reducing critical downtime through targeted recovery",
    image: "/assets/project-big-red-button.png",
    imageAlt: "Dark operational dashboard visualization for The Big RED BUTTON case study.",
    accent: "rose",
  },
  {
    category: "Critical Missions",
    title: "C4I - Beyond Clarity",
    href: "/experience/c4i-beyond-clarity",
    summary: "An operational system for awareness, coordination, trusted information, and accountable decisions.",
    image: "/assets/project-c4i-beyond-clarity.png",
    imageAlt: "Mission command interface visualization for C4I - Beyond Clarity.",
    accent: "eucalyptus",
  },
  {
    category: "Data Driven Design",
    title: "Monitoring and Product Intelligence",
    href: "/experience/monitoring-product-intelligence",
    summary: "Transforming Anecdotal Feedback into Data-Driven Strategy",
    image: "/assets/project-monitoring-product-intelligence.png",
    imageAlt: "Neon analytics chart visualization for Monitoring and Product Intelligence.",
    accent: "cyan",
  },
  {
    category: "KNOWLEDGE MANAGEMENT SYSTEM",
    title: "Nobody Reads the Manual",
    href: "/experience/nobody-reads-the-manual",
    summary: "Structuring expert knowledge before generative AI",
    image: "/assets/project-nobody-reads-manual.png",
    imageAlt: "Dark knowledge system workflow visualization for Nobody Reads the Manual.",
    accent: "violet",
  },
  {
    category: "Medical Software",
    title: "UX from the Heart",
    href: "/experience/ux-from-the-heart",
    summary: "Balancing innovation, precision, and clinical adoption",
    image: "/assets/project-ux-from-the-heart.png",
    imageAlt: "Medical software interface visualization for UX from the Heart.",
    accent: "aqua",
  },
] as const;

export const bigRedButtonCaseStudy = {
  slug: "the-big-red-button",
  category: "MONITOR MODULE",
  title: "The Big RED BUTTON",
  statement: "Reducing critical downtime through targeted recovery",
  heroAnchor: "the-big-red-button-hero",
  heroImage: "/assets/case-studies/big-red-button/hero-the-big-red-button.png",
  heroImageAlt: "Dark operational monitoring interface composition for The Big RED BUTTON case study.",
  intro: [
    "In a mission-critical naval system, downtime is an operational risk.",
    "Ship technicians had limited tools for diagnosing failures. When the application stopped working, they either contacted shore support or restarted the entire system.",
    "The initial request was simple:",
    "Build one button that resets everything.",
    "But a full reset would not solve the real problem. It could extend downtime, remove useful diagnostic information, and treat every failure as equally severe.",
    "I led the UX strategy and design of a Monitor Module that replaced blind resets with diagnosis, prevention, and role-based recovery tools.",
  ],
  snapshot: [
    ["Role", "Product Design Lead and UX Lead"],
    ["Domain", "Naval Command and Control systems"],
    ["Users", "Ship technicians, shore engineers, and system administrators"],
    ["Focus", "System health, fault diagnosis, recovery, and operational continuity"],
  ],
  sections: [
    {
      id: "the-reset-was-not-the-solution",
      title: "The Reset Was Not the Solution",
      body: [
        "The system operated across two very different environments.",
        "At sea, technicians needed fast and safe recovery without deep infrastructure knowledge.",
        "On shore, engineers needed technical detail, logs, and control over individual services.",
        "The existing experience served neither group well.",
        "Technicians saw technical errors they could not interpret.",
        "Engineers received incomplete reports and spent time searching through raw infrastructure data.",
        "The problem was not the absence of a reset button.",
        "It was the absence of a clear path from failure to action.",
      ],
      image: "/assets/case-studies/big-red-button/the-reset-reflex.png",
      imageAlt: "Red reset action reference visual.",
      variant: "problem",
    },
    {
      id: "translating-infrastructure-into-operational-meaning",
      title: "Translating Infrastructure Into Operational Meaning",
      body: [
        "Developers worked with Pods, Kafka, APIs, services, and databases.",
        "Technicians needed to know:",
      ],
      points: [
        "Is the system operational?",
        "Which capability is affected?",
        "Can I resolve the issue safely?",
        "Is expert support required?",
      ],
      after: [
        "I worked with architects and DevOps engineers to map common failure points and connect technical events to their operational impact.",
        "This created a translation layer between the system architecture and the people operating it.",
      ],
      image: "/assets/case-studies/big-red-button/monitor-from-panic-button-to-operational-intelligence.png",
      imageAlt: "From panic button to operational intelligence visual.",
      variant: "process",
    },
    {
      id: "smart-recovery-fix-what-failed",
      title: "Smart Recovery: Fix What Failed",
      body: [
        "Instead of one global reset, known failures were connected to focused recovery actions.",
        "When the system identified a recognized fault, the interface could present:",
      ],
      points: ["What failed", "Which capability was affected", "The severity of the issue", "A recommended action"],
      after: [
        "A contextual Fix Issue action could trigger a predefined technical process in the background, such as restarting a specific service.",
        "The technician did not need to understand the full architecture.",
        "The system provided the meaning and handled the technical execution.",
      ],
      image: "/assets/case-studies/big-red-button/smart-recovery-fix-what-failed.png",
      imageAlt: "Smart Recovery error and recommended fix interface.",
      variant: "feature",
    },
    {
      id: "prevention-before-recovery",
      title: "Prevention Before Recovery",
      body: [
        "Research revealed that some failures began during system configuration and startup.",
        "Different environments required different settings, authentication methods, and permissions. Missing or incorrect values could prevent the system from starting correctly.",
        "I designed a configuration flow that:",
      ],
      points: [
        "Adapted to sea and shore environments",
        "Exposed only relevant settings",
        "Validated mandatory information",
        "Prevented startup until critical conditions were met",
        "Distinguished production, staging, and training environments",
      ],
      after: ["The goal was not only to recover from failure.", "It was to prevent avoidable failures from reaching the user."],
      image: "/assets/case-studies/big-red-button/configuration-02.png",
      imageAlt: "System Configuration interface.",
      variant: "process",
    },
    {
      id: "expert-tools-without-expert-complexity-for-everyone",
      title: "Expert Tools Without Expert Complexity for Everyone",
      body: ["Shore engineers needed deeper access than ship technicians.", "The expert layer supported:"],
      points: [
        "Filtering logs by severity",
        "Filtering by service or component",
        "Selecting a focused time range",
        "Exporting only relevant data",
        "Tracking export status",
        "Moving from an alert to the relevant technical context",
      ],
      after: ["This reduced noise and created a more direct path from an operational issue to an engineering investigation."],
      gallery: [
        ["/assets/case-studies/big-red-button/expert-tools-logs.png", "Log filtering interface."],
        ["/assets/case-studies/big-red-button/expert-tools-errors-log.png", "Errors log screen."],
        ["/assets/case-studies/big-red-button/expert-tools-interface.png", "Expert tools interface."],
      ],
      variant: "gallery",
    },
    {
      id: "one-system-three-levels-of-control",
      title: "One System, Three Levels of Control",
      body: ["The module supported three different perspectives."],
      roles: [
        ["Ship Technician", "Clear status, operational impact, and guided recovery."],
        ["Shore Engineer", "Detailed diagnostics, log tools, and process-level control."],
        ["System Administrator", "A broader view of system health and recurring issues."],
      ],
      after: ["Each user received the information and actions needed for their responsibility."],
      image: "/assets/case-studies/big-red-button/screen.png",
      imageAlt: "System health interface screen.",
      variant: "feature",
    },
    {
      id: "what-changed",
      title: "What Changed",
      before: [
        "Technical failures appeared without operational context",
        "Ship technicians relied on shore support or full resets",
        "Configuration errors could cause immediate downtime",
        "Engineers searched through broad raw logs",
        "Different roles lacked a shared system-health view",
      ],
      afterList: [
        "Errors were connected to impact and next steps",
        "Known failures had targeted recovery actions",
        "Configuration was validated before startup",
        "Experts received focused diagnostic tools",
        "Role-based views supported one monitoring model",
      ],
      variant: "comparison",
    },
    {
      id: "from-recovery-to-prevention",
      title: "From Recovery to Prevention",
      body: [
        "Targeted diagnostics also created a more structured record of system failures.",
        "This foundation could support future capabilities such as:",
      ],
      points: [
        "Identifying recurring failure patterns",
        "Detecting degradation before a full outage",
        "Recommending preventive actions",
        "Supporting predictive maintenance",
      ],
      after: ["These capabilities were part of the future direction, not the initial implementation."],
      variant: "process",
    },
    {
      id: "the-product-shift",
      title: "The Product Shift",
      body: ["The project began with a request for one reset button.", "It became a broader system-health strategy:"],
      points: ["Translate the failure.", "Explain the impact.", "Apply the smallest safe action.", "Prevent the next one."],
      variant: "closing",
    },
  ],
} as const;

export const c4iCaseStudy = {
  slug: "c4i-beyond-clarity",
  role: "HEAD OF UX",
  category: "MISSION-CRITICAL C4I",
  title: "C4I - Beyond Clarity",
  statement: "Critical decisions need one clear operational picture.",
  heroImage: "/assets/case-studies/c4i-beyond-clarity/hero-01.png",
  heroImageAlt: "Dark C4I operational picture interface with maritime assets, command channels, and workflow status.",
  sections: [
    {
      id: "before-ux-organizational-alignment",
      label: "LEADERSHIP",
      title: "Before UX: organizational alignment.",
      body: "The four C4I layers revealed a system too complex to solve screen by screen. Before moving into UX definition, I aligned product, design, development, and stakeholders around priorities, decision flows, and implementation logic, creating the organizational process needed for clearer, faster, and more consistent design work.",
      points: [
        ["Operational Users", "Command and field teams needed fast comprehension, clear prioritization, and interfaces that reduce cognitive load under pressure."],
        ["Engineering Constraints", "The solution had to respect data flows, roles, permissions, release capacity, and technical dependencies."],
        ["Governance Challenge", "Move UX from request handling into a repeatable product capability for decisions, delivery, and learning."],
        ["Product Consistency", "Multiple interfaces needed to behave like one product: consistent language, reusable patterns, and shared ownership."],
      ],
    },
    {
      id: "four-pillars-one-shared-logic",
      label: "SYSTEM LOGIC",
      title: "Four pillars. One shared logic.",
      body: "The process connects strategy and UX across four C4I layers: clarifying the mission, mapping users and constraints, structuring decision flows, and validating trust in action.",
      points: [],
    },
    {
      id: "the-real-ux-was-invisible",
      label: "01 / INVISIBLE UX",
      title: "The real UX was invisible.",
      body: "In mission-critical systems, the best UX is often the action users no longer need to perform. Based on deep operational research, the work connected engineering logic, integrations, and algorithmic support into flows that felt almost unnoticeable under pressure.",
      points: [
        ["From separate forms to one action", "Users selected the relevant elements once. The system calculated fit, removed weak matches, and merged what belonged together."],
        ["Logic handled the slow work", "Matching, conflicts, and validation moved into system logic, reducing manual effort and preventing merge mistakes."],
        ["Trust stayed visible", "Supporting evidence, edit states, and override controls kept the user in charge before one validated object was created."],
      ],
    },
    {
      id: "defaults-made-each-workspace-feel-purpose-built",
      label: "02 / PERSONALIZATION",
      title: "Defaults made each workspace feel purpose-built.",
      body: "Instead of exposing the same tools and data to every operator, the system used profile settings, predefined choices, and dedicated tool sets to shape each workspace before use. Users could still adjust what mattered, but most of the operational context arrived ready.",
      points: [
        ["The workspace started ready", "Profile settings defined default tools, map state, forms, and operational views before the user began working."],
        ["Tools followed the role", "Each user saw the capabilities needed for their main actions, instead of navigating the full system every time."],
        ["Defaults stayed editable", "Local station presets supported rotating users, while still allowing fast adjustment when the context changed."],
      ],
    },
    {
      id: "designed-for-threat-response",
      label: "03 / SITUATIONAL AWARENESS",
      title: "Designed for threat response, not just information display.",
      body: "In this kind of critical system, the most important moment is how people respond to threats. The decision was to build a support layer for defensive workflows: fast classification and system recommendations for operators, and a command dashboard for leaders managing the full picture.",
      points: [
        ["Fast threat classification", "Classification sat next to system recommendations, grounding action in concrete evidence instead of scattered data."],
        ["A dashboard for the full picture", "Commanders received a top-level view of status, active processes, and decision progress across the workflow."],
        ["Proving the screen", "In military systems, a new screen can mean new hardware. The value had to be proven before it became part of the operational setup."],
      ],
    },
    {
      id: "ux-engineering-through-integration",
      label: "04 / UX ENGINEERING",
      title: "UX engineering through integration.",
      body: "A major part of the work was translating technical structures into operational flows. I mapped each field, value, data structure, and meaning, then clarified what the operator needed to see and what the system should handle in the background.",
      points: [
        ["Operational data mapping", "Each field was mapped by technical structure and operational value: what it supported, when it mattered, and whether it needed to be visible."],
        ["Interface-level integration", "Manual entry from paperwork became dedicated integrations that pushed operational data directly into structured forms."],
        ["Cleaner operator flows", "The system handled synchronization and population, saving time, reducing typing mistakes, and improving flow efficiency."],
      ],
    },
    {
      id: "screens-as-proof",
      label: "IMPACT",
      title: "Screens as proof.",
      body: "Each visual proves a product decision: pressure handled, responsibility protected, uncertainty exposed, accountability preserved.",
      points: [
        ["Awareness triggers action", "The shared picture became the entry point into defense, attack, or review workflows."],
        ["Authority is visible", "Permissions, responsibility, and allowed edits were part of the flow."],
        ["Decisions are reviewable", "Fusion, history, supporting data, and distribution records made trust inspectable."],
      ],
    },
    {
      id: "operational-resilience",
      label: "CLOSING REFLECTION",
      title: "Not screens. Operational resilience.",
      body: "ZOHARIM was designed for awareness, coordination, trusted information, and accountable decisions. My role was to help turn a massive classified system into a product experience people could scan, trust, coordinate through, and review when decisions mattered most.",
      points: [],
    },
  ],
} as const;

export const epdCaseStudy = {
  slug: "ux-from-the-heart",
  category: "EPD case study",
  title: "UX from the Heart",
  statement: "Balancing innovation, precision, and clinical adoption.",
  heroAnchor: "ux-from-the-heart",
  snapshot: [
    ["Role", "PM + UX Designer", "MVP definition"],
    ["Domain", "Cardiac imaging", "Electrophysiology"],
    ["Users", "EP physicians + techs", "Two users, one system"],
    ["Focus", "Clinical workflow", "Setup, visualization, safety feedback"],
    ["Outcome", "3-month MVP", "Launched at HRS 2019"],
  ],
  overview: {
    id: "project-overview",
    label: "Project overview",
    icon: "description",
    title: "Designing trust inside a life-critical clinical workflow.",
    body: [
      "KODEX-EPD is a cardiac imaging and mapping system for electrophysiology procedures, helping physicians navigate the heart with greater precision and without relying on radiation.",
      "The Alpha version exposed the real challenge: the system did not yet reflect the way clinical teams actually work. I joined as Project Manager and UX Designer to redefine the MVP and bridge company vision, technical development, and clinical adoption.",
    ],
  },
  sections: [
    {
      id: "two-users-operating-one-system",
      label: "Two roles, one screen",
      icon: "groups",
      title: "Two users operating one system",
      body: "KODEX-EPD had to support a physician beside the patient and a technician behind the glass. They watched the same display but performed different tasks through different controls.",
      roles: [
        ["medical_services", "The electrophysiologist", "Stands beside the patient, monitors screens, navigates the heart, and performs basic system actions through a foot pedal. Attention stays on the procedure."],
        ["settings_input_component", "The EP technician", "Works outside the room, configures the environment, manages complex system settings, and supports the physician throughout the procedure."],
      ],
      variant: "roles",
    },
    {
      id: "prepare-the-system-before-pressure",
      label: "Setup, before the procedure",
      icon: "build_circle",
      title: "Prepare the system before pressure enters the room.",
      body: "The Alpha experience required too much manual setup. I designed a logic-based Setup Wizard so the technician could configure the system across hardware, catheters, and contextual preferences.",
      points: [
        "Default and custom presets by procedure type",
        "Hardware-dependent options and catheter configurations",
      ],
      features: [
        ["Setup wizard", "Prepares the system for the clinical context."],
        ["Contextual UI", "Only relevant controls appear in view."],
        ["Clinical habits", "Preserves established mental models."],
      ],
      variant: "setup",
    },
    {
      id: "flexible-procedure-model",
      label: "When Alpha met clinical reality",
      icon: "alt_route",
      title: "Replacing a fixed sequence with a flexible procedure model",
      body: "Research showed the procedure was not linear. The flow changed by procedure type, active catheter, connected equipment, OR configuration, physician preference, and patient condition.",
      drivers: [
        ["01", "Procedure type", "Presets and paths adapt to the clinical case."],
        ["02", "Equipment state", "Tools and indicators reflect what is connected."],
        ["03", "Patient context", "The next step stays tied to procedural reality."],
      ],
      variant: "model",
    },
    {
      id: "clinical-habits-could-not-be-redesigned-away",
      label: "Core principle",
      icon: "favorite",
      title: "Clinical habits could not be redesigned away.",
      body: [
        "The redesign respected reversed anatomy views and ablation color conventions physicians already knew. The goal was to avoid adding unnecessary learning inside a high-risk procedure.",
        "Improving orientation inside the heart: catheter tip coloring, direction indicators, backward highlighting, clipping planes, and clear orientation cues made the 3D anatomy easier to interpret.",
      ],
      variant: "principle",
    },
    {
      id: "critical-information-stayed-in-view",
      label: "Keeping the procedure view complete",
      icon: "center_focus_strong",
      title: "Critical information stayed where attention already was.",
      body: "The redesign brought physiological data, system feedback, and technical support closer to the main workflow, without fragmenting attention.",
      timeline: [
        ["visibility", "Full orientation and adaptive view", "Continuous status, contextual messages, voice feedback, and high-risk confirmations stay visible throughout the procedure."],
        ["monitor_heart", "Critical data in the main view", "ECG signals and respiration graphs were integrated into the main procedure screen, eliminating the need for external monitors."],
        ["support_agent", "Contextual indicators and continuance feedback", "A third-party support technician could monitor progress in real time without disrupting the physician."],
      ],
      variant: "timeline",
    },
  ],
  outcome: {
    id: "from-alpha-to-clinical-mvp",
    label: "From Alpha to clinical MVP",
    icon: "rocket_launch",
    title: "From innovative Alpha to a clinically aligned MVP.",
    body: "The final MVP launched at the Heart Rhythm Society Convention in February 2019. It reflected real-world usage, from anatomy accuracy to touchpoint constraints, and contributed to a $293M acquisition by Philips.",
    stat: "$293M",
    statLabel: "Philips acquisition, July 2019",
  },
  takeaway: {
    id: "balancing-innovation-with-adoption",
    label: "Takeaway",
    icon: "favorite",
    title: "Balancing innovation with adoption",
    body: "This project reinforced that UX leadership in medi-tech is about helping advanced technology survive the reality of clinical use, without losing the trust and coordination patterns that high-risk procedures depend on.",
  },
} as const;

export const kmsCaseStudy = {
  slug: "nobody-reads-the-manual",
  category: "Knowledge Management System",
  title: "Nobody Reads the Manual",
  statement: "Structuring expert knowledge before generative AI",
  heroImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxcL-OuYY_mcApk_3VuXEbNsL4XXURb8wdHWD_YdENMzQQ_SHEn7C9m2B40A0e4VRRNk3PY4JltfOXsG7AG183_SOHMaFSup-bfxApu4zpwicq5-STQoVY3PBaDVsCUuZTRC0pr5-bIX8HvgzJWZ-JXS3rRJDLg5rjQjltEDfw_1QANFsxPcs2us3xUitgqZujQuKAuZPNFczQL2uCmyqWUNZpyxsIgpdcZqtFxlBBeVM3a4NJ7NBc3Q",
  heroImageAlt: "Howtool main interface.",
  visuals: {
    foundation: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDHjXdRrYr2ezviuzpV-BcHBYbLGFUf4_78Rzsk9smZ7FlpjALRaRdgs06UE6gThgTeX5ocH1S0tOBlKrrRykPOMTGRRs9WGeDWbPlx76VNWaOY7A97XxZP_bvf_uX_MkjCXsxpYDWXDiQ1T3rtWSOlatBtQGqkdyG4k9XCQ-OUzTcDG9E0jmSrV0kMvogRslr6amkapWrwIWMnOugPbv-EHRSy6ieeoTH15jNVpT-R3wxtC2yUBxOX9A",
      "Dashboard redesign.",
    ],
    editorToMobile: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBKz26WIztYh3FgCWKy9vlXigHZayyhVWkXhh_g2XS0m1FYc0uAjD5QIt8vXFbpo_KptTXFlqx2AJsMT4Stfk9fr6hAyn-gQ0xD3C0WM1RqFjt86K7UIMrbsresTnbiIFOYa5LfXjH-bFbsixMehwIlQERk_RJI2KV9uGu9olZMnXogMsLp8PVhW5bYmoPdDfyUBGcqaOlrC1Iz71-qkAFL0xT4bnQY0vHbVUJ4g6cWU5p9QsOIxaP9ng",
      "Editor to mobile translation.",
    ],
    process: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAoCVRrJTk3-A_qOYVjwLJHK-mQJVNzYzjsoHbb7qNP6_GY9PA8QWw7RUuRNre-D4twTxfdKXBJjqsuitJ-ZVkkPPwCjtex9_MaP8PRlTi_LCD3FKvbvdI14LMpbRa04axHsMBWYggi9p9sBjb_Re-p9NKdkJGdm6l1R8AU_dAgaC4Kd-sOd8dXF9_QOB5DoKVUaEbKYDKyODSHk__R_E2eAqRov8mQQvqRsyKroNOVx1mLQebYw9y60g",
      "Process flow diagram.",
    ],
    validation: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCGxdw2VPIGsJ2NclocdTAH3TbQf1IVzlN7cNHMPVw5gNEjGOtOIHBr8iKU5BqWenVE8xomK745aBB7zbn0kMyPpDG-lhskCJs97L3pn9BNwHlSC5CfrZJ0Zr-EXW593qgck3kK15tcWbUdT1uqmTVi02HrKrnAcqwkwky9XWv-dF3t4obsMasSAEB7QBRkTSUtsdXzQsWA8egn3S_s2ACPWkq4NklNy_jSNUSmlVCiju2HEWRiBL4-rA",
      "Validation panel.",
    ],
  },
  snapshot: [
    ["Role", "UX Team Lead + PM", "KMS redesign foundations", "person_outline"],
    ["Domain", "B2B SaaS", "Knowledge management platform", "settings"],
    ["Users", "Knowledge managers", "Creators, admins, operators", "groups"],
    ["Focus", "Content Management", "Preview, validation, guidance", "ads_click"],
  ],
  sections: [
    {
      id: "the-real-problem",
      label: "The Real Problem",
      title: "When creating the guide became harder than using it.",
      body: "Interviews with administrators and backlog review revealed a creation workflow that demanded too much memory, too much checking, and too much trial and error.",
      points: [
        ["Users lost orientation", "Complex navigation made it difficult to know where you were in a project and what still needed attention."],
        ["The editor did not match the result", "Creators could not reliably predict what technicians would receive in the final mobile guide."],
        ["Missing content surfaced too late", "The system gave too little guidance about incomplete items before publication."],
      ],
    },
    {
      id: "foundation-phase",
      label: "Foundation Phase",
      title: "Rebuilding the knowledge workspace.",
      body: "I facilitated an affinity-mapping workshop with the team to map existing and planned capabilities. Together, we grouped features by user intent, clarified permissions, removed redundant elements, and prioritized the roadmap.",
      points: ["Clear vertical navigation", "Two-column page structure", "Contextual tabs", "Role-based dashboards"],
    },
    {
      id: "editor-to-mobile",
      label: "Editor to Mobile",
      title: "Closing the gap between the KMS and the mobile experience.",
      body: "One of the biggest frustrations was the inconsistency between the editor and the final mobile guide. Layout problems, incorrect segmentation, and missing fields often appeared only after publication.",
      calloutTitle: "Design Response",
      callout: "Preview mode for full projects and individual items helped creators review the expected mobile result before release.",
    },
    {
      id: "process-model",
      label: "Process Model",
      title: "From expert logic to field action.",
      body: "The redesigned process created a clearer path from content creation to repeatable, step-by-step execution in the field.",
      points: ["Managers gained more control over content creation.", "Field technicians received more reliable interactive guidance through the mobile application."],
    },
    {
      id: "validation-before-release",
      label: "Validation Before Release",
      title: "Publishing with confidence.",
      body: "We mapped the most common publishing mistakes and introduced an automated validation layer. The system checked for missing or invalid information and blocked publication when critical issues remained unresolved.",
      calloutTitle: "Errors could now be identified before content reached the field.",
      callout: "This reduced repeated publishing cycles and gave creators more confidence in the result.",
    },
    {
      id: "contextual-guidance",
      label: "Contextual Guidance",
      title: "A manual should not need another manual.",
      body: "The product needed to support users without sending them to separate documentation. Guidance appeared inside the workflow, exactly when it was needed.",
      cardsTitle: "Adding info layers",
      points: [
        ["Tooltips", "Tooltip with simple instruction, triggered by mouse hover added to each component."],
        ["Empty states", "Empty states layout with simple explanation and supportive illustration were added to communicate with new users."],
        ["Wizards", "Set of wizards to guide users step-by-step through a set of actions from editing to publish their content."],
      ],
      secondaryTitle: "Enhance usability through education",
      secondaryBody: "To ease the learning curve and help users understand what they are required to do, the info layer was added using the following improvements:",
    },
  ],
} as const;
